config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "home#home"
  get "about", to: "home#about"
  get "nextpage", to: "home#nextpage"
  resources :articles 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence:true, length: {minimum: 6, maximum: 100}
    validates :description, presence:true, length: {minimum: 10, maximum: 200}
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    def show
        set_article
    end 

    def index
        @articles = Article.all 
    end

    def new 
        @article = Article.new 
    end 

    def edit 
        set_article
    end 

    def update 
        set_article
        if @article.update(article_params)
            flash[:notice] = "The article was updated successsfully"
            redirect_to article_path(@article)
        else 
            render 'edit'
        end
    end

    def destroy
        set_article
        @article.destroy 
        redirect_to articles_path
    end


    def create 
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = 'The article has been saved successfully!'
            redirect_to article_path(@article)
        
        else
            render 'new' 
        end
    end

    private 
    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description, :extra_information)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home 
    end

    def about 
    end

    def nextpage
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the article from being saved</h4>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %> 

<div class="row justify-content-center">
  <div class="col-10">
    <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
      <div class="form-group row">
        <%= f.label :title, class: "col-2 col-form-label text-light" %>
        <div class="col-10">
          <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
        </div>
      </div>
      <div class="form-group row">
        <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 4, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
      </div>
      <div class="form-group row">
        <%= f.label :extra_information, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :extra_information, rows: 4, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
      </div>
      <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>
      </div>
    <% end %>
  </div>
  <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Edit article</h1>
  <%= render 'form' %>
</div> 

app/views/articles/index.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Listing all articles</h1>
  <% @articles.each do |article| %> 
    <div class= "row justify-content-md-center">
	  <div class= "col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header">
            <%= article.title %>
        </div>
        <div class="card-body">
            <h5 class="card-title"><%= article.description %></h5>
            <p class="card-text"><%= article.extra_information %></p>
            <button type="button" class="btn btn-outline-primary"><%= link_to "View", article_path(article.id) %></button>
            <button type="button" class="btn btn-outline-success"><%= link_to "Edit", edit_article_path(article.id) %></button>
            <button type="button" class="btn btn-outline-danger"><%= link_to "Delete", article_path(article.id), method: "delete", data: {confirm: "Are you sure?"} %></button>
            
        </div>
        <div class="card-footer text-muted text-light">
            Created at <%= time_ago_in_words(article.created_at) %> ago & 
            Updated at <%= time_ago_in_words(article.updated_at) %> ago
        </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Create a new article</h1>
  <%= render 'form' %>
</div> 

app/views/articles/show.html.erb
<div id="page-content">
  <div class="container text-center">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
              <%= @article.title %>
          </div>
          <div class="card-body">
            <div class="card-text text-center"><%= simple_format(@article.description) %></div>
            <div class="card-text text-center"><%= simple_format(@article.extra_information) %></div>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
            </div>
            <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
                 edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class= "text-center">
    <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
  </div>
</div> 

app/views/home/about.html.erb
<h1>Here is our about page</h1>
<h1>Feel free to explore around here</h1>

<%= link_to "Articles", articles_path%>
<%= link_to "Home", root_path%>
<%= link_to "Nextpage", nextpage_path%>

app/views/home/home.html.erb
<div class="container">
    <div class="jumbotron text-center", id= 'home-container'>
        <h1 class="home1 display-4">Welcome to Rails Server!</h1>
        <p class="home2 lead">This is a simple server, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="home2 my-4">
        <p class= "home2">It uses utility classes for typography and spacing to space content out within the larger    container.</p>
        <p class= "row"></p>
        <p class= "row"></p>
        <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
    </div>
</div>

app/views/home/nextpage.html.erb
<h1>Here is the next page</h1>
<h1>Testing one two three</h1>

<%= link_to "Articles", articles_path%>
<%= link_to "About", about_path%>
<%= link_to "Home", root_path%>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>  

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#" id= logo>ALPHA BLOG</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link", id: "logo2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Articles",articles_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New Articles",new_article_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>          
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <div id= "page-content">
      <%= render 'layouts/navigation' %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <footer id="sticky-footer" class="py-4 bg-dark text-white">
      <div class="container text-center">
        <small>Copyright &copy; <%= link_to "Placee", "https://www.placee.com", class: "text-white" %></small>
      </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
  </body>
</html>